
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VPaned vpaned1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Entry entry1;

	private global::Gtk.Entry entry3;

	private global::Gtk.Entry entry5;

	private global::Gtk.Entry entry7;

	private global::Gtk.Entry entry9;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 229;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.Text = global::Mono.Unix.Catalog.GetString("Server");
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.vbox1.Add(this.entry1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entry1]));
		w1.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.Text = global::Mono.Unix.Catalog.GetString("Port");
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.vbox1.Add(this.entry3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entry3]));
		w2.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.Text = global::Mono.Unix.Catalog.GetString("Database");
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.vbox1.Add(this.entry5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entry5]));
		w3.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry7 = new global::Gtk.Entry();
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.Text = global::Mono.Unix.Catalog.GetString("Uid");
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '●';
		this.vbox1.Add(this.entry7);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entry7]));
		w4.Position = 3;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry9 = new global::Gtk.Entry();
		this.entry9.CanFocus = true;
		this.entry9.Name = "entry9";
		this.entry9.Text = global::Mono.Unix.Catalog.GetString("Pwd");
		this.entry9.IsEditable = true;
		this.entry9.InvisibleChar = '●';
		this.vbox1.Add(this.entry9);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entry9]));
		w5.Position = 4;
		this.vpaned1.Add(this.vbox1);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.vbox1]));
		w6.Resize = false;
		w6.Shrink = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Connecton");
		this.hbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
		w7.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Cancel");
		this.hbox1.Add(this.button3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button3]));
		w8.Position = 1;
		this.vpaned1.Add(this.hbox1);
		global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.hbox1]));
		w9.Resize = false;
		w9.Shrink = false;
		this.Add(this.vpaned1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.button1_Click);
	}
}
