
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Label label3;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button button50;

	private global::Gtk.Button button52;

	private global::Gtk.Button button54;

	private global::Gtk.Button button56;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button button65;

	private global::Gtk.Button button63;

	private global::Gtk.Button button60;

	private global::Gtk.Button button58;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button button67;

	private global::Gtk.Button button69;

	private global::Gtk.Button button71;

	private global::Gtk.Button button73;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Button button85;

	private global::Gtk.Button button77;

	private global::Gtk.Button button79;

	private global::Gtk.Button button81;

	private global::Gtk.Label GtkLabel15;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame1.LabelYalign = 0F;
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Homogeneous = true;
		this.vbox5.Spacing = 6;
		this.vbox5.BorderWidth = ((uint)(3));
		// Container child vbox5.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.Ypad = 15;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Answer Goes Here");
		this.label3.UseUnderline = true;
		this.vbox5.Add(this.label3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Homogeneous = true;
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button50 = new global::Gtk.Button();
		this.button50.CanFocus = true;
		this.button50.Name = "button50";
		this.button50.UseUnderline = true;
		this.button50.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox3.Add(this.button50);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button50]));
		w2.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button52 = new global::Gtk.Button();
		this.button52.CanFocus = true;
		this.button52.Name = "button52";
		this.button52.UseUnderline = true;
		this.button52.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox3.Add(this.button52);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button52]));
		w3.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button54 = new global::Gtk.Button();
		this.button54.CanFocus = true;
		this.button54.Name = "button54";
		this.button54.UseUnderline = true;
		this.button54.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox3.Add(this.button54);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button54]));
		w4.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button56 = new global::Gtk.Button();
		this.button56.CanFocus = true;
		this.button56.Name = "button56";
		this.button56.UseUnderline = true;
		this.button56.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox3.Add(this.button56);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button56]));
		w5.Position = 3;
		this.vbox5.Add(this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox3]));
		w6.Position = 1;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Homogeneous = true;
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button65 = new global::Gtk.Button();
		this.button65.CanFocus = true;
		this.button65.Name = "button65";
		this.button65.UseUnderline = true;
		this.button65.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox5.Add(this.button65);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button65]));
		w7.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button63 = new global::Gtk.Button();
		this.button63.CanFocus = true;
		this.button63.Name = "button63";
		this.button63.UseUnderline = true;
		this.button63.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox5.Add(this.button63);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button63]));
		w8.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button60 = new global::Gtk.Button();
		this.button60.CanFocus = true;
		this.button60.Name = "button60";
		this.button60.UseUnderline = true;
		this.button60.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox5.Add(this.button60);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button60]));
		w9.Position = 2;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button58 = new global::Gtk.Button();
		this.button58.CanFocus = true;
		this.button58.Name = "button58";
		this.button58.UseUnderline = true;
		this.button58.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox5.Add(this.button58);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button58]));
		w10.Position = 3;
		this.vbox5.Add(this.hbox5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
		w11.Position = 2;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Homogeneous = true;
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button67 = new global::Gtk.Button();
		this.button67.CanFocus = true;
		this.button67.Name = "button67";
		this.button67.UseUnderline = true;
		this.button67.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox7.Add(this.button67);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button67]));
		w12.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button69 = new global::Gtk.Button();
		this.button69.CanFocus = true;
		this.button69.Name = "button69";
		this.button69.UseUnderline = true;
		this.button69.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox7.Add(this.button69);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button69]));
		w13.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button71 = new global::Gtk.Button();
		this.button71.CanFocus = true;
		this.button71.Name = "button71";
		this.button71.UseUnderline = true;
		this.button71.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox7.Add(this.button71);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button71]));
		w14.Position = 2;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button73 = new global::Gtk.Button();
		this.button73.CanFocus = true;
		this.button73.Name = "button73";
		this.button73.UseUnderline = true;
		this.button73.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox7.Add(this.button73);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button73]));
		w15.Position = 3;
		this.vbox5.Add(this.hbox7);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
		w16.Position = 3;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Homogeneous = true;
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button85 = new global::Gtk.Button();
		this.button85.CanFocus = true;
		this.button85.Name = "button85";
		this.button85.UseUnderline = true;
		this.button85.FocusOnClick = false;
		this.button85.Relief = ((global::Gtk.ReliefStyle)(2));
		this.button85.Label = global::Mono.Unix.Catalog.GetString("  ");
		this.hbox9.Add(this.button85);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button85]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button77 = new global::Gtk.Button();
		this.button77.CanFocus = true;
		this.button77.Name = "button77";
		this.button77.UseUnderline = true;
		this.button77.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox9.Add(this.button77);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button77]));
		w18.Position = 1;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button79 = new global::Gtk.Button();
		this.button79.CanFocus = true;
		this.button79.Name = "button79";
		this.button79.UseUnderline = true;
		this.button79.FocusOnClick = false;
		this.button79.Relief = ((global::Gtk.ReliefStyle)(2));
		this.button79.Label = global::Mono.Unix.Catalog.GetString("  ");
		this.hbox9.Add(this.button79);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button79]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button81 = new global::Gtk.Button();
		this.button81.CanFocus = true;
		this.button81.Name = "button81";
		this.button81.UseUnderline = true;
		this.button81.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbox9.Add(this.button81);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button81]));
		w20.Position = 3;
		this.vbox5.Add(this.hbox9);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
		w21.Position = 4;
		this.GtkAlignment.Add(this.vbox5);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel15 = new global::Gtk.Label();
		this.GtkLabel15.Name = "GtkLabel15";
		this.GtkLabel15.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Calculator</b>");
		this.GtkLabel15.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel15;
		this.Add(this.frame1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 532;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
