
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Label label;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button add;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button sub;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.Button div;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Button button85;

	private global::Gtk.Button button;

	private global::Gtk.Button equals;

	private global::Gtk.Button mul;

	private global::Gtk.Label GtkLabel15;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame1.LabelYalign = 0F;
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Homogeneous = true;
		this.vbox5.Spacing = 6;
		this.vbox5.BorderWidth = ((uint)(3));
		// Container child vbox5.Gtk.Box+BoxChild
		this.label = new global::Gtk.Label();
		this.label.Name = "label";
		this.label.Ypad = 15;
		this.label.UseUnderline = true;
		this.label.Justify = ((global::Gtk.Justification)(2));
		this.vbox5.Add(this.label);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Homogeneous = true;
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Events = ((global::Gdk.EventMask)(256));
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox3.Add(this.button1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button1]));
		w2.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Events = ((global::Gdk.EventMask)(256));
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox3.Add(this.button2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button2]));
		w3.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Events = ((global::Gdk.EventMask)(256));
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox3.Add(this.button3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button3]));
		w4.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.add = new global::Gtk.Button();
		this.add.CanFocus = true;
		this.add.Events = ((global::Gdk.EventMask)(256));
		this.add.Name = "add";
		this.add.UseUnderline = true;
		this.add.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox3.Add(this.add);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.add]));
		w5.Position = 3;
		this.vbox5.Add(this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox3]));
		w6.Position = 1;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Homogeneous = true;
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Events = ((global::Gdk.EventMask)(256));
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox5.Add(this.button4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button4]));
		w7.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Events = ((global::Gdk.EventMask)(256));
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox5.Add(this.button5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button5]));
		w8.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Events = ((global::Gdk.EventMask)(256));
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox5.Add(this.button6);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button6]));
		w9.Position = 2;
		// Container child hbox5.Gtk.Box+BoxChild
		this.sub = new global::Gtk.Button();
		this.sub.CanFocus = true;
		this.sub.Events = ((global::Gdk.EventMask)(256));
		this.sub.Name = "sub";
		this.sub.UseUnderline = true;
		this.sub.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox5.Add(this.sub);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.sub]));
		w10.Position = 3;
		this.vbox5.Add(this.hbox5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
		w11.Position = 2;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Homogeneous = true;
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Events = ((global::Gdk.EventMask)(256));
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox7.Add(this.button7);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button7]));
		w12.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Events = ((global::Gdk.EventMask)(256));
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox7.Add(this.button8);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button8]));
		w13.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Events = ((global::Gdk.EventMask)(256));
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox7.Add(this.button9);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button9]));
		w14.Position = 2;
		// Container child hbox7.Gtk.Box+BoxChild
		this.div = new global::Gtk.Button();
		this.div.CanFocus = true;
		this.div.Events = ((global::Gdk.EventMask)(256));
		this.div.Name = "div";
		this.div.UseUnderline = true;
		this.div.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox7.Add(this.div);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.div]));
		w15.Position = 3;
		this.vbox5.Add(this.hbox7);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
		w16.Position = 3;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Homogeneous = true;
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button85 = new global::Gtk.Button();
		this.button85.CanFocus = true;
		this.button85.Name = "button85";
		this.button85.UseUnderline = true;
		this.button85.Label = global::Mono.Unix.Catalog.GetString("  clear");
		this.hbox9.Add(this.button85);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button85]));
		w17.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button = new global::Gtk.Button();
		this.button.CanFocus = true;
		this.button.Events = ((global::Gdk.EventMask)(256));
		this.button.Name = "button";
		this.button.UseUnderline = true;
		this.button.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox9.Add(this.button);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button]));
		w18.Position = 1;
		// Container child hbox9.Gtk.Box+BoxChild
		this.equals = new global::Gtk.Button();
		this.equals.CanFocus = true;
		this.equals.Name = "equals";
		this.equals.UseUnderline = true;
		this.equals.Label = global::Mono.Unix.Catalog.GetString("  =");
		this.hbox9.Add(this.equals);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.equals]));
		w19.Position = 2;
		// Container child hbox9.Gtk.Box+BoxChild
		this.mul = new global::Gtk.Button();
		this.mul.CanFocus = true;
		this.mul.Events = ((global::Gdk.EventMask)(256));
		this.mul.Name = "mul";
		this.mul.UseUnderline = true;
		this.mul.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbox9.Add(this.mul);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.mul]));
		w20.Position = 3;
		this.vbox5.Add(this.hbox9);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
		w21.Position = 4;
		this.GtkAlignment.Add(this.vbox5);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel15 = new global::Gtk.Label();
		this.GtkLabel15.Name = "GtkLabel15";
		this.GtkLabel15.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Calculator</b>");
		this.GtkLabel15.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel15;
		this.Add(this.frame1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 532;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.NumOne_Click);
		this.button2.Clicked += new global::System.EventHandler(this.NumTwo_Click);
		this.button3.Clicked += new global::System.EventHandler(this.NumThree_Click);
		this.add.Clicked += new global::System.EventHandler(this.FuncAdd_Click);
		this.button4.Clicked += new global::System.EventHandler(this.NumFour_Click);
		this.button5.Clicked += new global::System.EventHandler(this.NumFive_Click);
		this.button6.Clicked += new global::System.EventHandler(this.NumSix_Click);
		this.sub.Clicked += new global::System.EventHandler(this.FuncSub_Click);
		this.button7.Clicked += new global::System.EventHandler(this.NumSeven_Click);
		this.button8.Clicked += new global::System.EventHandler(this.NumEight_Click);
		this.button9.Clicked += new global::System.EventHandler(this.NumNine_Click);
		this.div.Clicked += new global::System.EventHandler(this.FuncDiv_Click);
		this.button85.Clicked += new global::System.EventHandler(this.Clear_Click);
		this.button.Clicked += new global::System.EventHandler(this.NumZero_Click);
		this.equals.Clicked += new global::System.EventHandler(this.Equals_Click);
		this.mul.Clicked += new global::System.EventHandler(this.FuncMul_Click);
	}
}
